### ISSUE TITLE
[RTCP] Not in CPAN ?

### ISSUE THREAD

**Issue by rdupz** [njh/perl-net-rtp#1]
Hello,

The RTCP support seems to have been added after the RTP support.
Can I ask you why the RTCP support is absent from CPAN ? Is it unstable ?

Best regards,

**Comment by njh** [comment]
Sorry I haven't done any work on the RTP perl module for quite a long time and can't remember the state of RTCP.

It is likely that the work was partly complete and then unreleased.

Please submit a Pull Request if you have any fixes/improvements for RTCP.

nick.
